'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

export default function ProfilePage() {
  const router = useRouter()
  const [form, setForm] = useState({ educationLevel: '', district: '', state: '', currentCourse: '', institution: '', interests: '', careerGoals: '', subjects: '' })
  const [completion, setCompletion] = useState(0)
  const [message, setMessage] = useState('')

  useEffect(() => { fetch('/api/profile').then(async (response) => { if (response.status === 401) return router.replace('/login'); const data = await response.json(); const profile = data.profile; if (profile) setForm({ educationLevel: profile.educationLevel ?? '', district: profile.district ?? '', state: profile.state ?? '', currentCourse: profile.currentCourse ?? '', institution: profile.institution ?? '', interests: (profile.interests ?? []).join(', '), careerGoals: (profile.careerGoals ?? []).join(', '), subjects: (profile.subjects ?? []).join(', ') }); setCompletion(data.completion?.percentage ?? 0) }) }, [router])
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage('Saving...'); const response = await fetch('/api/profile', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, age: undefined, interests: form.interests.split(',').map((item) => item.trim()).filter(Boolean), careerGoals: form.careerGoals.split(',').map((item) => item.trim()).filter(Boolean), subjects: form.subjects.split(',').map((item) => item.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message ?? 'Unable to save profile.'); setCompletion(data.completion.percentage); setMessage('Profile saved successfully.'); if (data.completion.completed) router.push('/'); }
  return <main className="min-h-screen bg-[#f6faf9] px-6 py-12 text-slate-900"><div className="mx-auto max-w-2xl rounded-3xl bg-white p-8 shadow-sm"><p className="text-sm font-semibold text-teal-700">CareerSetu</p><h1 className="mt-2 text-3xl font-black">Build your career profile</h1><p className="mt-2 text-slate-500">Complete your profile so we can personalize your path.</p><div className="mt-6"><div className="flex justify-between text-sm font-semibold"><span>Profile completion</span><span>{completion}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{ width: `${completion}%` }} /></div></div><form onSubmit={submit} className="mt-8 grid gap-4 sm:grid-cols-2">{[['educationLevel','Education level'],['district','District'],['state','State'],['currentCourse','Current course'],['institution','Institution'],['interests','Interests (comma separated)'],['careerGoals','Career goals (comma separated)'],['subjects','Subjects (comma separated)']].map(([key, label]) => <label key={key} className="grid gap-2 text-sm font-semibold"><span>{label}</span>{key === 'educationLevel' ? <select value={form.educationLevel} onChange={(event) => update(key as keyof typeof form, event.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 font-normal"><option value="">Select level</option><option value="class_10">Class 10</option><option value="class_12">Class 12</option><option value="diploma">Diploma</option><option value="undergraduate">Undergraduate</option><option value="postgraduate">Postgraduate</option></select> : <input value={form[key as keyof typeof form]} onChange={(event) => update(key as keyof typeof form, event.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-teal-500" />}</label>)}<button className="mt-4 rounded-xl bg-teal-600 px-5 py-3 font-bold text-white hover:bg-teal-700 sm:col-span-2">Save profile</button></form>{message && <p className="mt-4 text-sm font-semibold text-teal-700">{message}</p>}</div></main>
}
